import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { auth } from "../auth/firebase";
import { useEffect, useState } from "react";
import { DocumentData } from "firebase/firestore";
const Home: NextPage = () => {
  const [data, setData] = useState<DocumentData>([]);
  useEffect(() => {
    fetch("/api/products")
      .then((res) => res.json())
      .then((data: DocumentData) => setData(data?.products));
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data &&
          data.map((product: DocumentData, index: number) => (
            <div key={index}>
              <p>{product.product_name}</p>
              <Image
                src={product.product_image}
                alt={product.product_name}
                width={200}
                height={200}
                objectFit={"cover"}
              />
            </div>
          ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
